name: Build Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test
        run: go test ./...

      - name: Build
        run: |
          LDFLAGS='-s -w'
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -trimpath -ldflags="$LDFLAGS" -o Fdoc-windows-amd64.exe .
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="$LDFLAGS" -o Fdoc-linux-amd64 .
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags="$LDFLAGS" -o Fdoc-darwin-amd64 .
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -trimpath -ldflags="$LDFLAGS" -o Fdoc-linux-arm64 .
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags="$LDFLAGS" -o Fdoc-darwin-arm64 .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fdoc-binaries
          path: |
            Fdoc-windows-amd64.exe
            Fdoc-linux-amd64
            Fdoc-linux-arm64
            Fdoc-darwin-amd64
            Fdoc-darwin-arm64